name: build
# From now in android
# https://github.com/android/nowinandroid

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: { }

jobs:
  setup-job:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    outputs:
      android: ${{ steps.changes.outputs.android }}
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Check code changes related to Android
        uses: dorny/paths-filter@v3.0.2
        id: changes
        with:
          filters: |
            android:
              - '**/*.kt'
              - '**/*.kts'
              - '**/*.xml'
              - 'gradle/libs.versions.toml'

  build:
    needs: setup-job
    if: ${{ needs.setup-job.outputs.android == 'true' }}
    permissions:
      contents: read

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - uses: ./.github/actions/setup-java

      - run: ./gradlew :app-android:assembleDevDebug --stacktrace

      - name: Upload build outputs (APKs)
        uses: actions/upload-artifact@v4
        with:
          name: build-outputs
          path: app-android/build/outputs
          retention-days: 14
